//@version=4

//一、单线走势：确认市场长期趋势走向
// strategy(title="Moving Average", shorttitle="MA", overlay=true)
// len = input(5, minval=1, title="Length")
// src = input(close, title="Source")
// offset = input(title="Offset", type=input.integer, defval=0, minval=-500, maxval=500)
// out = sma(src, len)
// plot(out, color=color.blue, title="MA", offset=offset)
// to_long=crossover(close,out)
// to_short=crossunder(close,out)
// strategy.entry("long",strategy.long,qty=1000,when=to_long)
// strategy.close("long",qty=1000,when=to_short)

// strategy.entry("short",strategy.short,qty=1000,when=to_short)
// strategy.close("short",qty=1000,when=to_long)


//@version=4
//二、双线交叉：快慢两条ma，查看交叉处
// strategy(title="Moving Average", shorttitle="MA", overlay=true)
// len1 = input(8, minval=1, title="ma quick")
// len2 = input(50, minval=1, title="ma slow")
// src = input(close, title="Source")
// offset = input(title="Offset", type=input.integer, defval=0, minval=-500, maxval=500)
// ma_quick = wma(src, len1)
// ma_slow = sma(src, len2)
// plot(ma_quick, color=color.blue, title="MA-Quick", offset=offset)
// plot(ma_slow, color=color.red, title="MA-Slow", offset=offset)

// to_long=crossover(ma_quick,ma_slow)
// to_short=crossunder(ma_quick,ma_slow)


// strategy.entry("long",strategy.long,qty=1000,when=to_long)
// strategy.close("long",qty=1000,when=to_short)

// strategy.entry("short",strategy.short,qty=1000,when=to_short)
// strategy.close("short",qty=1000,when=to_long)
//三、多线组合：根据bar是否击穿多条线 而减半、清仓、抄底


//sma 简单平均 
//ema指数平均 dema 双倍指数平均更敏感
//wma 权重平均 越近权重越高 更敏感 

strategy(title="Moving Average", shorttitle="MA", overlay=true)
len1 = input(5, minval=1, title="ma fast")
len2 = input(34, minval=1, title="ma slow")
src = input(close, title="Source")
offset = input(title="Offset", type=input.integer, defval=0, minval=-500, maxval=500)
//fast_e1=ema(src, len1)
//fast_e2=ema(fast_e1,len1)
//ma_fast = 2*fast_e1-fast_e2

ma_fast=ema(src,len1)
// ma_fast=wma(src,len1)

slow_e1=ema(src, len2)
slow_e2=ema(slow_e1,len2)
ma_slow = 2*slow_e1-slow_e2


plot(ma_fast, color=color.red, title="MA-Fast", offset=offset)
plot(ma_slow, color=color.blue, title="MA-Slow")

to_long=crossover(ma_fast,ma_slow)
to_short=crossunder(ma_fast,ma_slow)


strategy.entry("long",strategy.long,qty=1000,when=to_long)
strategy.close("long",qty=1000,when=to_short)

strategy.entry("short",strategy.short,qty=1000,when=to_short)
strategy.close("short",qty=1000,when=to_long)

// strategy("Partial exit demo")
// if bar_index > 100 and bar_index <125
//     strategy.entry("buy", strategy.long, 3, when=strategy.position_size <= 0)//3手
// strategy.exit("bracket1", "buy",  1, profit = 3000,loss = 3000)// 3%
// strategy.exit("bracket2", "buy",  profit=2000, loss=2000)
// plot(strategy.equity)